/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUserRouteImport } from './routes/_app.user'
import { Route as AppTaskIndexRouteImport } from './routes/_app.task.index'
import { Route as AppTaskIdRouteImport } from './routes/_app.task.$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRoute,
} as any)
const AppTaskIndexRoute = AppTaskIndexRouteImport.update({
  id: '/task/',
  path: '/task/',
  getParentRoute: () => AppRoute,
} as any)
const AppTaskIdRoute = AppTaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/user': typeof AppUserRoute
  '/task/$id': typeof AppTaskIdRoute
  '/task/': typeof AppTaskIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/user': typeof AppUserRoute
  '/': typeof AppIndexRoute
  '/task/$id': typeof AppTaskIdRoute
  '/task': typeof AppTaskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/user': typeof AppUserRoute
  '/_app/': typeof AppIndexRoute
  '/_app/task/$id': typeof AppTaskIdRoute
  '/_app/task/': typeof AppTaskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/' | '/sign-in' | '/user' | '/task/$id' | '/task/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/sign-in' | '/user' | '/' | '/task/$id' | '/task'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/sign-in'
    | '/_app/user'
    | '/_app/'
    | '/_app/task/$id'
    | '/_app/task/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user': {
      id: '/_app/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/task/': {
      id: '/_app/task/'
      path: '/task'
      fullPath: '/task/'
      preLoaderRoute: typeof AppTaskIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/task/$id': {
      id: '/_app/task/$id'
      path: '/task/$id'
      fullPath: '/task/$id'
      preLoaderRoute: typeof AppTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppUserRoute: typeof AppUserRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTaskIdRoute: typeof AppTaskIdRoute
  AppTaskIndexRoute: typeof AppTaskIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUserRoute: AppUserRoute,
  AppIndexRoute: AppIndexRoute,
  AppTaskIdRoute: AppTaskIdRoute,
  AppTaskIndexRoute: AppTaskIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
